<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="OakNorth Test Suite" duration-ms="40035" started-at="2017-06-13T16:39:36Z" finished-at="2017-06-13T16:40:16Z">
    <groups>
    </groups>
    <test name="TestSuite" duration-ms="40035" started-at="2017-06-13T16:39:36Z" finished-at="2017-06-13T16:40:16Z">
      <class name="com.oaknorth.testcases.TestCase1">
        <test-method status="PASS" signature="browseropen()[pri:0, instance:com.oaknorth.testcases.TestCase1@12f41634]" name="browseropen" is-config="true" duration-ms="6853" started-at="2017-06-13T22:09:36Z" finished-at="2017-06-13T22:09:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browseropen -->
        <test-method status="PASS" signature="tc1()[pri:0, instance:com.oaknorth.testcases.TestCase1@12f41634]" name="tc1" duration-ms="33162" started-at="2017-06-13T22:09:43Z" finished-at="2017-06-13T22:10:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="FAIL" signature="browserclose()[pri:0, instance:com.oaknorth.testcases.TestCase1@12f41634]" name="browserclose" is-config="true" duration-ms="0" started-at="2017-06-13T22:10:16Z" finished-at="2017-06-13T22:10:16Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[javax.mail.AuthenticationFailedException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: javax.mail.AuthenticationFailedException
	at com.oaknorth.reports.Email_SMS_Report.mailSending(Email_SMS_Report.java:125)
	at com.oaknorth.config.CommonMethods.browserclose(CommonMethods.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:308)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: javax.mail.AuthenticationFailedException
	at javax.mail.Service.connect(Service.java:306)
	at javax.mail.Service.connect(Service.java:156)
	at javax.mail.Service.connect(Service.java:105)
	at javax.mail.Transport.send0(Transport.java:168)
	at javax.mail.Transport.send(Transport.java:98)
	at com.oaknorth.reports.Email_SMS_Report.mailSending(Email_SMS_Report.java:116)
	... 19 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserclose -->
      </class> <!-- com.oaknorth.testcases.TestCase1 -->
    </test> <!-- TestSuite -->
  </suite> <!-- OakNorth Test Suite -->
</testng-results>
